<?php
declare(strict_types=1);
require_once("Player.php");

class Dealer extends Player
{

    public function hit(Deck $deck)
    {
       do{
           parent::hit($deck); // TODO: Change the autogenerated stub
       }
       while($this->getScore() <= 15);

    }

}